category: "stego"
name:     "Восьмиборье"
points:   150
author:   abbradar
description: |
    <p>При осмотре места преступления был обнаружен диск с разнообразными файлами. Сможете отыскать на нём секретную информацию?</p>
generator: generate.py
