category: "stegano"
name:     "Восьмиборье"
points:   150
author:   abbradar
description: |
    <p>При осмотре места преступления был обнаружен диск с разнообразными файлами. Сможете отыскать на нём секретную информацию?</p>
    <pre>Данные на диске запрятаны не в содержимом файлов. Шестнадцатеричный редактор может помочь вам в этом расследовании.</pre>
generator: generate.py
