category:    "recon"
name:        "Огни города поменьше"
points:      400
author:      "kalan"
description: >
    <p>Вам нужно найти точку съёмки этого прекрасного вида. На этот раз в файле даже есть геометка, вот только она совершенно бесполезна.</p>

    <p><em>Примечание 1.</em> У вас есть восемь попыток. Проверяющая система беспощадна и принимает лишь точный ответ — прочитайте правила ввода и не тратьте попытки зря.</p>
    <p><em>Примечание 2.</em> Проверяющая система не содержит известных авторам уязвимостей. Настойчивые попытки получить флаг способом, отличным от ввода верного ответа в рамках предоставленного количества попыток, считаются атаками на инфраструктуру с соответствующими последствиями для команды.</p>

    <p>Ваши одноразовые коды:</p>
    <ul>
        <li>{{ code0 }}</li>
        <li>{{ code1 }}</li>
        <li>{{ code2 }}</li>
        <li>{{ code3 }}</li>
        <li>{{ code4 }}</li>
        <li>{{ code5 }}</li>
        <li>{{ code6 }}</li>
        <li>{{ code7 }}</li>
    </ul>
generator: generate.py
daemon: server/start_server.sh
daemon_socket: "smallercitylights.sock"
