category: "crypto"
name:     "Арбатско-Покровская линия?"
points:   150
author:   vanyaklimenko
description: |
    <p>Вот сеанс работы в некой среде:</p>
    <pre>
          ⎕IO ← 0
          A ← 'abcdefghijklmnopqrstuvwxy_1234567890'
          I ← (6 6 ⍴ 1 + ⍳6)+⍉(10 × 6 6 ⍴ 1 + ⍳6)
          S ← 6 6 ⍴ A
          E ← {⌈/⌈/ (~⍵ ⍳ S) × I}
          E¨flag
    {{ ciphertext }}
    </pre>
    <p>Мы так и не поняли, что это за среда, но очень рады результату, ведь теперь вы тоже, скорее всего, ничего не поймёте.</p>
generator: generate.py
