category:    "stegano"
name:        "ЦНИИВТ"
points:      150
author:      "nsychev"
description: >
    <p>Устроился системным администратором в Центральный НИИ вычислительной техники. На второй неделе работы обнаружил в локальной сети какой-то странный компьютер. Поспрашивал у коллег — все впервые слышат о нём, даже не знают, на каком этаже он стоит.</p>
    <p>Искал пару дней, в итоге нашёл его в подсобке под слоем пыли — такое ощущение, что лет 30 к нему никто не прикасался. Самое удивительное — это то, что он каким-то образом подключен к интернету, и на нём даже открыт порт. При подключении просит пароль, я его раздобыл в архиве. Но вместо данных сервер шлёт какой-то мусор.</p>
    <p>Поможете разобраться? Вдруг там что-то важное!</p>
generator: generate.py
daemon: app/start_server.sh
daemon_socket: soviet.sock
daemon_socket_type: tcp
daemon_socket_out_port: 17792
